---
- name: Configure node-1
  hosts: node-1
  become: true
  tasks:
  - name: Install web server
    apt:
      name: nginx
  - name: Copy index.html
    copy:
      src: ./index.html
      dest: /var/www/html/index.html
  - name: mkdir backup directory
    file:
      path: /backup
      state: directory
      mode: '0777'
  - name: Change directory ownership, group and permissions
    file:
      path: /var/www/html
      owner: www-data
      group: gitlab-runner
      recurse: yes
      mode: '0775'


  - name: Add Gitlab GPG apt Key
    apt_key:
      url: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
      state: present
  - name: Add Gitlab Repository
    apt_repository:
      repo: deb https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ bionic main
      state: present
  - name: Update apt update cache and install gitlab-runner
    apt:
      name: gitlab-runner
      state: present
      update_cache: yes
  - name: Add node-2 to host file
    lineinfile:
      path: /etc/hosts
# Need use variable
      line: 192.168.10.24 gitlab

  - name: Adding user gitlab-runner
    user:
      name: gitlab-runner
      groups: www-data

- name: Configure node-2
  hosts: node-2
  become: true
  tasks:
  - name: Uninstall old versions
    apt:
      name:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent
  - name: Install required system packages
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - python3-pip
      state: present
      update_cache: yes
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: Update apt and install docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
      update_cache: yes
  - name: Install Docker Module for Python
    pip:
      name: docker
  - name: Deploy Gitlab docker container
    docker_container:
      name: gitlab
      image: gitlab/gitlab-ce
      state: started
      hostname: gitlab
      volumes:
        - /data
        - /config
        - /logs
      ports:
        - "80:80"
        - "443:443"
        - "8822:22"
